# Peers and Agents can register in Sip I/O location service
- apiVersion: v1draft1
  kind: Agent
  metadata:
    name: John Doe
  spec:
    credentials:
      username: mohsen
      secret: '123456'
    domains: [192.168.1.188]
- kind: Agent
  apiVersion: v1draft1
  metadata:
    name: Janie Doe
  spec:
    credentials:
      username: hasan
      secret: '123456'
    domains: [192.168.1.188]
- kind: Agent
  apiVersion: v1draft1
  metadata:
    name: Jack Doe
  spec:
    credentials:
      username: mamad
      secret: '123456'
    domains: [192.168.1.188]
