- apiVersion: v1draft1
  kind: Domain
  metadata:
    name: Ocean Central Office
  spec:
    context:
      domainUri: 192.168.1.103
      egressPolicy:
        rule: .*        # See the Location Service Rules for information about this parameter
        didRef: DID0001
- apiVersion: v1draft1
  kind: Domain
  metadata:
    name: Ocean NY Office
  spec:
    context:
      domainUri: sip.ny.ocean.com
