- apiVersion: v1draft1
  kind: Gateway
  metadata:
    name: sip.mohsen.work gateway
    ref:  GW0001
  spec:
    regService:
      host: sip.mohsen.work:5050
      credentials:
        username: 'sipio'
        secret: '1234'
      transport: udp
