- apiVersion: v1draft1
  kind: Gateway
  metadata:
    name: Provider 1
    ref:  GW0001
  spec:
    regService:
      host: sip.mohsen.work:5050
      credentials:
        username: 'hasan'
        secret: '1234'
      transport: udp
