- apiVersion: v1draft1
  kind: Gateway
  metadata:
    name: Provider 1
    ref:  GW0001
  spec:
    regService:
      host: sip.provider1.net
      credentials:
        username: 'user'
        secret: 'secret'
      transport: udp
      registries:
        - sip2.provider1.net
- apiVersion: v1draft1
  kind: Gateway
  metadata:
    name: Provider 2
    ref:  GW0002
  spec:
    regService:
      host: sip.provider2.net
      credentials:
        username: 'user'
        secret: 'secret'
      transport: tcp
